logisticRegression:
    penalty : 'l2'
    dual : False 
    tol: 0.0001 
    C : 1.0
    fit_intercept : True
    intercept_scaling : 1 
    class_weight : !!null
    random_state : !!null
    solver : 'lbfgs' 
    max_iter : 200
    multi_class : 'auto'
    verbose : 0
    warm_start : False
    n_jobs : -1
    l1_ratio : !!null   

svc:
    C : 1.0
    kernel : 'linear'
    degree : 3
    gamma : 'scale'
    coef0 : 0.0
    shrinking : True
    probability : True 
    tol : 0.001
    cache_size : 3000
    class_weight : 'balanced'
    verbose : False
    max_iter : -1
    decision_function_shape : 'ovr'
    break_ties : False
    random_state : !!null

randomForestClassifier:
    n_estimators : 100 
    criterion : 'gini' 
    max_depth : !!null
    min_samples_split : 2
    min_samples_leaf : 1 
    min_weight_fraction_leaf : 0.0
    max_features : 'auto' 
    max_leaf_nodes : !!null
    min_impurity_decrease : 0.0
    min_impurity_split : !!null
    bootstrap : True
    oob_score : False
    n_jobs: -1
    random_state : !!null
    verbose : 0
    warm_start : False
    class_weight : !!null
    ccp_alpha : 0.0
    max_samples : !!null

train_test_split:
    test_size : 0.20
    random_state : 42

resample:
    replace : True 
    n_samples  : 284315
    random_state : 123

roc_auc_score:
    average : 'macro'
    sample_weight : !!null
    max_fpr : !!null
    multi_class : 'raise'
    labels : !!null

StratifiedKFold:
    n_splits : 5
